name: RTL Hardware Verification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  simulate_cache:
    runs-on: self-hosted 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo yum update -y
          sudo yum install -y python3 iverilog

      - name: Run Python Verification Script
        run: python3 scripts/run_and_parse.py